name: Check for vehicle updates

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '24 1,3,5,7,9,11,13,15,17,19,21,23 * * *'

jobs:
  check-vehicles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Clone nudl tool
        run: |
          git clone https://github.com/chenxiaolong/nudl

      - name: Build nudl tool
        run: |
          cd nudl
          cargo build --release

      - name: Run nudl
        run: |
          cd nudl/target/release
          ./nudl list -b hyundai

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git add *
          git diff --quiet && git diff --staged --quiet || git commit -am 'API changes [ci skip]'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
